version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./node_modules:/app/node_modules # Bind local node_modules to container's node_modules
      - .:/app # Bind current directory to `/app` inside container

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev  
    volumes:
      - ./node_modules:/app/node_modules 
      - .:/app
    command: ["npm", "run", "test"]
